"""Official Indonesian region codes -- GENERATED, DO NOT EDIT BY HAND.

Regenerate with `py -3.11 tools/build_regions.py` after updating the source CSV.
Source: kota_kabupaten_provinsi.csv (38 provinces, 514 kabupaten/kota).

`kode_wilayah` encodes the hierarchy: "96" is a province, "96.01" a kabupaten/kota inside it.
`REGION_TO_PROVINCE` keys are normalised (casefolded, whitespace collapsed, KAB./KOTA prefix
stripped) and carry both the bare and prefixed forms, so "bandung" and "kota bandung" both hit.
"""

# code -> province name, Title Case for display
PROVINCES = {
    '11': 'Aceh',
    '12': 'Sumatera Utara',
    '13': 'Sumatera Barat',
    '14': 'Riau',
    '15': 'Jambi',
    '16': 'Sumatera Selatan',
    '17': 'Bengkulu',
    '18': 'Lampung',
    '19': 'Kepulauan Bangka Belitung',
    '21': 'Kepulauan Riau',
    '31': 'DKI Jakarta',
    '32': 'Jawa Barat',
    '33': 'Jawa Tengah',
    '34': 'DI Yogyakarta',
    '35': 'Jawa Timur',
    '36': 'Banten',
    '51': 'Bali',
    '52': 'Nusa Tenggara Barat',
    '53': 'Nusa Tenggara Timur',
    '61': 'Kalimantan Barat',
    '62': 'Kalimantan Tengah',
    '63': 'Kalimantan Selatan',
    '64': 'Kalimantan Timur',
    '65': 'Kalimantan Utara',
    '71': 'Sulawesi Utara',
    '72': 'Sulawesi Tengah',
    '73': 'Sulawesi Selatan',
    '74': 'Sulawesi Tenggara',
    '75': 'Gorontalo',
    '76': 'Sulawesi Barat',
    '81': 'Maluku',
    '82': 'Maluku Utara',
    '91': 'Papua',
    '92': 'Papua Barat',
    '93': 'Papua Selatan',
    '94': 'Papua Tengah',
    '95': 'Papua Pegunungan',
    '96': 'Papua Barat Daya',
}

# code -> kabupaten/kota name, rank prefix kept
REGENCIES = {
    '11.01': 'Kab. Aceh Selatan',
    '11.02': 'Kab. Aceh Tenggara',
    '11.03': 'Kab. Aceh Timur',
    '11.04': 'Kab. Aceh Tengah',
    '11.05': 'Kab. Aceh Barat',
    '11.06': 'Kab. Aceh Besar',
    '11.07': 'Kab. Pidie',
    '11.08': 'Kab. Aceh Utara',
    '11.09': 'Kab. Simeulue',
    '11.10': 'Kab. Aceh Singkil',
    '11.11': 'Kab. Bireuen',
    '11.12': 'Kab. Aceh Barat Daya',
    '11.13': 'Kab. Gayo Lues',
    '11.14': 'Kab. Aceh Jaya',
    '11.15': 'Kab. Nagan Raya',
    '11.16': 'Kab. Aceh Tamiang',
    '11.17': 'Kab. Bener Meriah',
    '11.18': 'Kab. Pidie Jaya',
    '11.71': 'Kota Banda Aceh',
    '11.72': 'Kota Sabang',
    '11.73': 'Kota Lhokseumawe',
    '11.74': 'Kota Langsa',
    '11.75': 'Kota Subulussalam',
    '12.01': 'Kab. Tapanuli Tengah',
    '12.02': 'Kab. Tapanuli Utara',
    '12.03': 'Kab. Tapanuli Selatan',
    '12.04': 'Kab. Nias',
    '12.05': 'Kab. Langkat',
    '12.06': 'Kab. Karo',
    '12.07': 'Kab. Deli Serdang',
    '12.08': 'Kab. Simalungun',
    '12.09': 'Kab. Asahan',
    '12.10': 'Kab. Labuhanbatu',
    '12.11': 'Kab. Dairi',
    '12.12': 'Kab. Toba',
    '12.13': 'Kab. Mandailing Natal',
    '12.14': 'Kab. Nias Selatan',
    '12.15': 'Kab. Pakpak Bharat',
    '12.16': 'Kab. Humbang Hasundutan',
    '12.17': 'Kab. Samosir',
    '12.18': 'Kab. Serdang Bedagai',
    '12.19': 'Kab. Batu Bara',
    '12.20': 'Kab. Padang Lawas Utara',
    '12.21': 'Kab. Padang Lawas',
    '12.22': 'Kab. Labuhanbatu Selatan',
    '12.23': 'Kab. Labuhanbatu Utara',
    '12.24': 'Kab. Nias Utara',
    '12.25': 'Kab. Nias Barat',
    '12.71': 'Kota Medan',
    '12.72': 'Kota Pematangsiantar',
    '12.73': 'Kota Sibolga',
    '12.74': 'Kota Tanjung Balai',
    '12.75': 'Kota Binjai',
    '12.76': 'Kota Tebing Tinggi',
    '12.77': 'Kota Padang Sidempuan',
    '12.78': 'Kota Gunungsitoli',
    '13.01': 'Kab. Pesisir Selatan',
    '13.02': 'Kab. Solok',
    '13.03': 'Kab. Sijunjung',
    '13.04': 'Kab. Tanah Datar',
    '13.05': 'Kab. Padang Pariaman',
    '13.06': 'Kab. Agam',
    '13.07': 'Kab. Lima Puluh Kota',
    '13.08': 'Kab. Pasaman',
    '13.09': 'Kab. Kepulauan Mentawai',
    '13.10': 'Kab. Dharmasraya',
    '13.11': 'Kab. Solok Selatan',
    '13.12': 'Kab. Pasaman Barat',
    '13.71': 'Kota Padang',
    '13.72': 'Kota Solok',
    '13.73': 'Kota Sawahlunto',
    '13.74': 'Kota Padang Panjang',
    '13.75': 'Kota Bukittinggi',
    '13.76': 'Kota Payakumbuh',
    '13.77': 'Kota Pariaman',
    '14.01': 'Kab. Kampar',
    '14.02': 'Kab. Indragiri Hulu',
    '14.03': 'Kab. Bengkalis',
    '14.04': 'Kab. Indragiri Hilir',
    '14.05': 'Kab. Pelalawan',
    '14.06': 'Kab. Rokan Hulu',
    '14.07': 'Kab. Rokan Hilir',
    '14.08': 'Kab. Siak',
    '14.09': 'Kab. Kuantan Singingi',
    '14.10': 'Kab. Kepulauan Meranti',
    '14.71': 'Kota Pekanbaru',
    '14.72': 'Kota Dumai',
    '15.01': 'Kab. Kerinci',
    '15.02': 'Kab. Merangin',
    '15.03': 'Kab. Sarolangun',
    '15.04': 'Kab. Batanghari',
    '15.05': 'Kab. Muaro Jambi',
    '15.06': 'Kab. Tanjung Jabung Barat',
    '15.07': 'Kab. Tanjung Jabung Timur',
    '15.08': 'Kab. Bungo',
    '15.09': 'Kab. Tebo',
    '15.71': 'Kota Jambi',
    '15.72': 'Kota Sungai Penuh',
    '16.01': 'Kab. Ogan Komering Ulu',
    '16.02': 'Kab. Ogan Komering Ilir',
    '16.03': 'Kab. Muara Enim',
    '16.04': 'Kab. Lahat',
    '16.05': 'Kab. Musi Rawas',
    '16.06': 'Kab. Musi Banyuasin',
    '16.07': 'Kab. Banyuasin',
    '16.08': 'Kab. Ogan Komering Ulu Timur',
    '16.09': 'Kab. Ogan Komering Ulu Selatan',
    '16.10': 'Kab. Ogan Ilir',
    '16.11': 'Kab. Empat Lawang',
    '16.12': 'Kab. Penukal Abab Lematang Ilir',
    '16.13': 'Kab. Musi Rawas Utara',
    '16.71': 'Kota Palembang',
    '16.72': 'Kota Pagar Alam',
    '16.73': 'Kota Lubuk Linggau',
    '16.74': 'Kota Prabumulih',
    '17.01': 'Kab. Bengkulu Selatan',
    '17.02': 'Kab. Rejang Lebong',
    '17.03': 'Kab. Bengkulu Utara',
    '17.04': 'Kab. Kaur',
    '17.05': 'Kab. Seluma',
    '17.06': 'Kab. Muko Muko',
    '17.07': 'Kab. Lebong',
    '17.08': 'Kab. Kepahiang',
    '17.09': 'Kab. Bengkulu Tengah',
    '17.71': 'Kota Bengkulu',
    '18.01': 'Kab. Lampung Selatan',
    '18.02': 'Kab. Lampung Tengah',
    '18.03': 'Kab. Lampung Utara',
    '18.04': 'Kab. Lampung Barat',
    '18.05': 'Kab. Tulang Bawang',
    '18.06': 'Kab. Tanggamus',
    '18.07': 'Kab. Lampung Timur',
    '18.08': 'Kab. Way Kanan',
    '18.09': 'Kab. Pesawaran',
    '18.10': 'Kab. Pringsewu',
    '18.11': 'Kab. Mesuji',
    '18.12': 'Kab. Tulang Bawang Barat',
    '18.13': 'Kab. Pesisir Barat',
    '18.71': 'Kota Bandar Lampung',
    '18.72': 'Kota Metro',
    '19.01': 'Kab. Bangka',
    '19.02': 'Kab. Belitung',
    '19.03': 'Kab. Bangka Selatan',
    '19.04': 'Kab. Bangka Tengah',
    '19.05': 'Kab. Bangka Barat',
    '19.06': 'Kab. Belitung Timur',
    '19.71': 'Kota Pangkal Pinang',
    '21.01': 'Kab. Bintan',
    '21.02': 'Kab. Karimun',
    '21.03': 'Kab. Natuna',
    '21.04': 'Kab. Lingga',
    '21.05': 'Kab. Kepulauan Anambas',
    '21.71': 'Kota Batam',
    '21.72': 'Kota Tanjung Pinang',
    '31.01': 'Kab. Adm. Kep. Seribu',
    '31.71': 'Kota Adm. Jakarta Pusat',
    '31.72': 'Kota Adm. Jakarta Utara',
    '31.73': 'Kota Adm. Jakarta Barat',
    '31.74': 'Kota Adm. Jakarta Selatan',
    '31.75': 'Kota Adm. Jakarta Timur',
    '32.01': 'Kab. Bogor',
    '32.02': 'Kab. Sukabumi',
    '32.03': 'Kab. Cianjur',
    '32.04': 'Kab. Bandung',
    '32.05': 'Kab. Garut',
    '32.06': 'Kab. Tasikmalaya',
    '32.07': 'Kab. Ciamis',
    '32.08': 'Kab. Kuningan',
    '32.09': 'Kab. Cirebon',
    '32.10': 'Kab. Majalengka',
    '32.11': 'Kab. Sumedang',
    '32.12': 'Kab. Indramayu',
    '32.13': 'Kab. Subang',
    '32.14': 'Kab. Purwakarta',
    '32.15': 'Kab. Karawang',
    '32.16': 'Kab. Bekasi',
    '32.17': 'Kab. Bandung Barat',
    '32.18': 'Kab. Pangandaran',
    '32.71': 'Kota Bogor',
    '32.72': 'Kota Sukabumi',
    '32.73': 'Kota Bandung',
    '32.74': 'Kota Cirebon',
    '32.75': 'Kota Bekasi',
    '32.76': 'Kota Depok',
    '32.77': 'Kota Cimahi',
    '32.78': 'Kota Tasikmalaya',
    '32.79': 'Kota Banjar',
    '33.01': 'Kab. Cilacap',
    '33.02': 'Kab. Banyumas',
    '33.03': 'Kab. Purbalingga',
    '33.04': 'Kab. Banjarnegara',
    '33.05': 'Kab. Kebumen',
    '33.06': 'Kab. Purworejo',
    '33.07': 'Kab. Wonosobo',
    '33.08': 'Kab. Magelang',
    '33.09': 'Kab. Boyolali',
    '33.10': 'Kab. Klaten',
    '33.11': 'Kab. Sukoharjo',
    '33.12': 'Kab. Wonogiri',
    '33.13': 'Kab. Karanganyar',
    '33.14': 'Kab. Sragen',
    '33.15': 'Kab. Grobogan',
    '33.16': 'Kab. Blora',
    '33.17': 'Kab. Rembang',
    '33.18': 'Kab. Pati',
    '33.19': 'Kab. Kudus',
    '33.20': 'Kab. Jepara',
    '33.21': 'Kab. Demak',
    '33.22': 'Kab. Semarang',
    '33.23': 'Kab. Temanggung',
    '33.24': 'Kab. Kendal',
    '33.25': 'Kab. Batang',
    '33.26': 'Kab. Pekalongan',
    '33.27': 'Kab. Pemalang',
    '33.28': 'Kab. Tegal',
    '33.29': 'Kab. Brebes',
    '33.71': 'Kota Magelang',
    '33.72': 'Kota Surakarta',
    '33.73': 'Kota Salatiga',
    '33.74': 'Kota Semarang',
    '33.75': 'Kota Pekalongan',
    '33.76': 'Kota Tegal',
    '34.01': 'Kab. Kulon Progo',
    '34.02': 'Kab. Bantul',
    '34.03': 'Kab. Gunungkidul',
    '34.04': 'Kab. Sleman',
    '34.71': 'Kota Yogyakarta',
    '35.01': 'Kab. Pacitan',
    '35.02': 'Kab. Ponorogo',
    '35.03': 'Kab. Trenggalek',
    '35.04': 'Kab. Tulungagung',
    '35.05': 'Kab. Blitar',
    '35.06': 'Kab. Kediri',
    '35.07': 'Kab. Malang',
    '35.08': 'Kab. Lumajang',
    '35.09': 'Kab. Jember',
    '35.10': 'Kab. Banyuwangi',
    '35.11': 'Kab. Bondowoso',
    '35.12': 'Kab. Situbondo',
    '35.13': 'Kab. Probolinggo',
    '35.14': 'Kab. Pasuruan',
    '35.15': 'Kab. Sidoarjo',
    '35.16': 'Kab. Mojokerto',
    '35.17': 'Kab. Jombang',
    '35.18': 'Kab. Nganjuk',
    '35.19': 'Kab. Madiun',
    '35.20': 'Kab. Magetan',
    '35.21': 'Kab. Ngawi',
    '35.22': 'Kab. Bojonegoro',
    '35.23': 'Kab. Tuban',
    '35.24': 'Kab. Lamongan',
    '35.25': 'Kab. Gresik',
    '35.26': 'Kab. Bangkalan',
    '35.27': 'Kab. Sampang',
    '35.28': 'Kab. Pamekasan',
    '35.29': 'Kab. Sumenep',
    '35.71': 'Kota Kediri',
    '35.72': 'Kota Blitar',
    '35.73': 'Kota Malang',
    '35.74': 'Kota Probolinggo',
    '35.75': 'Kota Pasuruan',
    '35.76': 'Kota Mojokerto',
    '35.77': 'Kota Madiun',
    '35.78': 'Kota Surabaya',
    '35.79': 'Kota Batu',
    '36.01': 'Kab. Pandeglang',
    '36.02': 'Kab. Lebak',
    '36.03': 'Kab. Tangerang',
    '36.04': 'Kab. Serang',
    '36.71': 'Kota Tangerang',
    '36.72': 'Kota Cilegon',
    '36.73': 'Kota Serang',
    '36.74': 'Kota Tangerang Selatan',
    '51.01': 'Kab. Jembrana',
    '51.02': 'Kab. Tabanan',
    '51.03': 'Kab. Badung',
    '51.04': 'Kab. Gianyar',
    '51.05': 'Kab. Klungkung',
    '51.06': 'Kab. Bangli',
    '51.07': 'Kab. Karangasem',
    '51.08': 'Kab. Buleleng',
    '51.71': 'Kota Denpasar',
    '52.01': 'Kab. Lombok Barat',
    '52.02': 'Kab. Lombok Tengah',
    '52.03': 'Kab. Lombok Timur',
    '52.04': 'Kab. Sumbawa',
    '52.05': 'Kab. Dompu',
    '52.06': 'Kab. Bima',
    '52.07': 'Kab. Sumbawa Barat',
    '52.08': 'Kab. Lombok Utara',
    '52.71': 'Kota Mataram',
    '52.72': 'Kota Bima',
    '53.01': 'Kab. Kupang',
    '53.02': 'Kab Timor Tengah Selatan',
    '53.03': 'Kab. Timor Tengah Utara',
    '53.04': 'Kab. Belu',
    '53.05': 'Kab. Alor',
    '53.06': 'Kab. Flores Timur',
    '53.07': 'Kab. Sikka',
    '53.08': 'Kab. Ende',
    '53.09': 'Kab. Ngada',
    '53.10': 'Kab. Manggarai',
    '53.11': 'Kab. Sumba Timur',
    '53.12': 'Kab. Sumba Barat',
    '53.13': 'Kab. Lembata',
    '53.14': 'Kab. Rote Ndao',
    '53.15': 'Kab. Manggarai Barat',
    '53.16': 'Kab. Nagekeo',
    '53.17': 'Kab. Sumba Tengah',
    '53.18': 'Kab. Sumba Barat Daya',
    '53.19': 'Kab. Manggarai Timur',
    '53.20': 'Kab. Sabu Raijua',
    '53.21': 'Kab. Malaka',
    '53.71': 'Kota Kupang',
    '61.01': 'Kab. Sambas',
    '61.02': 'Kab. Mempawah',
    '61.03': 'Kab. Sanggau',
    '61.04': 'Kab. Ketapang',
    '61.05': 'Kab. Sintang',
    '61.06': 'Kab. Kapuas Hulu',
    '61.07': 'Kab. Bengkayang',
    '61.08': 'Kab. Landak',
    '61.09': 'Kab. Sekadau',
    '61.10': 'Kab. Melawi',
    '61.11': 'Kab. Kayong Utara',
    '61.12': 'Kab. Kubu Raya',
    '61.71': 'Kota Pontianak',
    '61.72': 'Kota Singkawang',
    '62.01': 'Kab. Kotawaringin Barat',
    '62.02': 'Kab. Kotawaringin Timur',
    '62.03': 'Kab. Kapuas',
    '62.04': 'Kab. Barito Selatan',
    '62.05': 'Kab. Barito Utara',
    '62.06': 'Kab. Katingan',
    '62.07': 'Kab. Seruyan',
    '62.08': 'Kab. Sukamara',
    '62.09': 'Kab. Lamandau',
    '62.10': 'Kab. Gunung Mas',
    '62.11': 'Kab. Pulang Pisau',
    '62.12': 'Kab. Murung Raya',
    '62.13': 'Kab. Barito Timur',
    '62.71': 'Kota Palangkaraya',
    '63.01': 'Kab. Tanah Laut',
    '63.02': 'Kab. Kotabaru',
    '63.03': 'Kab. Banjar',
    '63.04': 'Kab. Barito Kuala',
    '63.05': 'Kab. Tapin',
    '63.06': 'Kab. Hulu Sungai Selatan',
    '63.07': 'Kab. Hulu Sungai Tengah',
    '63.08': 'Kab. Hulu Sungai Utara',
    '63.09': 'Kab. Tabalong',
    '63.10': 'Kab. Tanah Bumbu',
    '63.11': 'Kab. Balangan',
    '63.71': 'Kota Banjarmasin',
    '63.72': 'Kota Banjarbaru',
    '64.01': 'Kab. Paser',
    '64.02': 'Kab. Kutai Kartanegara',
    '64.03': 'Kab. Berau',
    '64.07': 'Kab. Kutai Barat',
    '64.08': 'Kab. Kutai Timur',
    '64.09': 'Kab. Penajam Paser Utara',
    '64.11': 'Kab. Mahakam Ulu',
    '64.71': 'Kota Balikpapan',
    '64.72': 'Kota Samarinda',
    '64.74': 'Kota Bontang',
    '65.01': 'Kab. Bulungan',
    '65.02': 'Kab. Malinau',
    '65.03': 'Kab. Nunukan',
    '65.04': 'Kab. Tana Tidung',
    '65.71': 'Kota Tarakan',
    '71.01': 'Kab. Bolaang Mongondow',
    '71.02': 'Kab. Minahasa',
    '71.03': 'Kab. Kepulauan Sangihe',
    '71.04': 'Kab. Kepulauan Talaud',
    '71.05': 'Kab. Minahasa Selatan',
    '71.06': 'Kab. Minahasa Utara',
    '71.07': 'Kab. Minahasa Tenggara',
    '71.08': 'Kab. Bolaang Mongondow Utara',
    '71.09': 'Kab. Kep. Siau Tagulandang Biaro',
    '71.10': 'Kab. Bolaang Mongondow Timur',
    '71.11': 'Kab. Bolaang Mongondow Selatan',
    '71.71': 'Kota Manado',
    '71.72': 'Kota Bitung',
    '71.73': 'Kota Tomohon',
    '71.74': 'Kota Kotamobagu',
    '72.01': 'Kab. Banggai',
    '72.02': 'Kab. Poso',
    '72.03': 'Kab. Donggala',
    '72.04': 'Kab. Toli Toli',
    '72.05': 'Kab. Buol',
    '72.06': 'Kab. Morowali',
    '72.07': 'Kab. Banggai Kepulauan',
    '72.08': 'Kab. Parigi Moutong',
    '72.09': 'Kab. Tojo Una Una',
    '72.10': 'Kab. Sigi',
    '72.11': 'Kab. Banggai Laut',
    '72.12': 'Kab. Morowali Utara',
    '72.71': 'Kota Palu',
    '73.01': 'Kab. Kepulauan Selayar',
    '73.02': 'Kab. Bulukumba',
    '73.03': 'Kab. Bantaeng',
    '73.04': 'Kab. Jeneponto',
    '73.05': 'Kab. Takalar',
    '73.06': 'Kab. Gowa',
    '73.07': 'Kab. Sinjai',
    '73.08': 'Kab. Bone',
    '73.09': 'Kab. Maros',
    '73.10': 'Kab. Pangkajene Dan Kepulauan',
    '73.11': 'Kab. Barru',
    '73.12': 'Kab. Soppeng',
    '73.13': 'Kab. Wajo',
    '73.14': 'Kab. Sidenreng Rappang',
    '73.15': 'Kab. Pinrang',
    '73.16': 'Kab. Enrekang',
    '73.17': 'Kab. Luwu',
    '73.18': 'Kab. Tana Toraja',
    '73.22': 'Kab. Luwu Utara',
    '73.24': 'Kab. Luwu Timur',
    '73.26': 'Kab. Toraja Utara',
    '73.71': 'Kota Makassar',
    '73.72': 'Kota Parepare',
    '73.73': 'Kota Palopo',
    '74.01': 'Kab. Kolaka',
    '74.02': 'Kab. Konawe',
    '74.03': 'Kab. Muna',
    '74.04': 'Kab. Buton',
    '74.05': 'Kab. Konawe Selatan',
    '74.06': 'Kab. Bombana',
    '74.07': 'Kab. Wakatobi',
    '74.08': 'Kab. Kolaka Utara',
    '74.09': 'Kab. Konawe Utara',
    '74.10': 'Kab. Buton Utara',
    '74.11': 'Kab. Kolaka Timur',
    '74.12': 'Kab. Konawe Kepulauan',
    '74.13': 'Kab. Muna Barat',
    '74.14': 'Kab. Buton Tengah',
    '74.15': 'Kab. Buton Selatan',
    '74.71': 'Kota Kendari',
    '74.72': 'Kota Bau Bau',
    '75.01': 'Kab. Gorontalo',
    '75.02': 'Kab. Boalemo',
    '75.03': 'Kab. Bone Bolango',
    '75.04': 'Kab. Pohuwato',
    '75.05': 'Kab. Gorontalo Utara',
    '75.71': 'Kota Gorontalo',
    '76.01': 'Kab. Pasangkayu',
    '76.02': 'Kab. Mamuju',
    '76.03': 'Kab. Mamasa',
    '76.04': 'Kab. Polewali Mandar',
    '76.05': 'Kab. Majene',
    '76.06': 'Kab. Mamuju Tengah',
    '81.01': 'Kab. Maluku Tengah',
    '81.02': 'Kab. Maluku Tenggara',
    '81.03': 'Kab. Kepulauan Tanimbar',
    '81.04': 'Kab. Buru',
    '81.05': 'Kab. Seram Bagian Timur',
    '81.06': 'Kab. Seram Bagian Barat',
    '81.07': 'Kab. Kepulauan Aru',
    '81.08': 'Kab. Maluku Barat Daya',
    '81.09': 'Kab. Buru Selatan',
    '81.71': 'Kota Ambon',
    '81.72': 'Kota Tual',
    '82.01': 'Kab. Halmahera Barat',
    '82.02': 'Kab. Halmahera Tengah',
    '82.03': 'Kab. Halmahera Utara',
    '82.04': 'Kab. Halmahera Selatan',
    '82.05': 'Kab. Kepulauan Sula',
    '82.06': 'Kab. Halmahera Timur',
    '82.07': 'Kab. Pulau Morotai',
    '82.08': 'Kab. Pulau Taliabu',
    '82.71': 'Kota Ternate',
    '82.72': 'Kota Tidore Kepulauan',
    '91.03': 'Kab. Jayapura',
    '91.05': 'Kab. Kepulauan Yapen',
    '91.06': 'Kab. Biak Numfor',
    '91.10': 'Kab. Sarmi',
    '91.11': 'Kab. Keerom',
    '91.15': 'Kab. Waropen',
    '91.19': 'Kab. Supiori',
    '91.20': 'Kab. Mamberamo Raya',
    '91.71': 'Kota Jayapura',
    '92.02': 'Kab. Manokwari',
    '92.03': 'Kab. Fak Fak',
    '92.06': 'Kab. Teluk Bintuni',
    '92.07': 'Kab. Teluk Wondama',
    '92.08': 'Kab. Kaimana',
    '92.11': 'Kab. Manokwari Selatan',
    '92.12': 'Kab. Pegunungan Arfak',
    '93.01': 'Kab. Merauke',
    '93.02': 'Kab. Boven Digoel',
    '93.03': 'Kab. Mappi',
    '93.04': 'Kab. Asmat',
    '94.01': 'Kab. Nabire',
    '94.02': 'Kab. Puncak Jaya',
    '94.03': 'Kab. Paniai',
    '94.04': 'Kab. Mimika',
    '94.05': 'Kab. Puncak',
    '94.06': 'Kab. Dogiyai',
    '94.07': 'Kab. Intan Jaya',
    '94.08': 'Kab. Deiyai',
    '95.01': 'Kab. Jayawijaya',
    '95.02': 'Kab Pegunungan Bintang',
    '95.03': 'Kab. Yahukimo',
    '95.04': 'Kab. Tolikara',
    '95.05': 'Kab. Mamberamo Tengah',
    '95.06': 'Kab. Yalimo',
    '95.07': 'Kab. Lanny Jaya',
    '95.08': 'Kab. Nduga',
    '96.01': 'Kab. Sorong',
    '96.02': 'Kab. Sorong Selatan',
    '96.03': 'Kab. Raja Ampat',
    '96.04': 'Kab. Tambrauw',
    '96.05': 'Kab. Maybrat',
    '96.71': 'Kota Sorong',
}

# normalised kabupaten/kota name -> province name
REGION_TO_PROVINCE = {
    'aceh barat': 'Aceh',
    'aceh barat daya': 'Aceh',
    'aceh besar': 'Aceh',
    'aceh jaya': 'Aceh',
    'aceh selatan': 'Aceh',
    'aceh singkil': 'Aceh',
    'aceh tamiang': 'Aceh',
    'aceh tengah': 'Aceh',
    'aceh tenggara': 'Aceh',
    'aceh timur': 'Aceh',
    'aceh utara': 'Aceh',
    'adm. kep. seribu': 'DKI Jakarta',
    'agam': 'Sumatera Barat',
    'alor': 'Nusa Tenggara Timur',
    'ambon': 'Maluku',
    'asahan': 'Sumatera Utara',
    'asmat': 'Papua Selatan',
    'badung': 'Bali',
    'balangan': 'Kalimantan Selatan',
    'balikpapan': 'Kalimantan Timur',
    'banda aceh': 'Aceh',
    'bandar lampung': 'Lampung',
    'bandung': 'Jawa Barat',
    'bandung barat': 'Jawa Barat',
    'banggai': 'Sulawesi Tengah',
    'banggai kepulauan': 'Sulawesi Tengah',
    'banggai laut': 'Sulawesi Tengah',
    'bangka': 'Kepulauan Bangka Belitung',
    'bangka barat': 'Kepulauan Bangka Belitung',
    'bangka selatan': 'Kepulauan Bangka Belitung',
    'bangka tengah': 'Kepulauan Bangka Belitung',
    'bangkalan': 'Jawa Timur',
    'bangli': 'Bali',
    'banjar': 'Jawa Barat',
    'banjarbaru': 'Kalimantan Selatan',
    'banjarmasin': 'Kalimantan Selatan',
    'banjarnegara': 'Jawa Tengah',
    'bantaeng': 'Sulawesi Selatan',
    'bantul': 'DI Yogyakarta',
    'banyuasin': 'Sumatera Selatan',
    'banyumas': 'Jawa Tengah',
    'banyuwangi': 'Jawa Timur',
    'barito kuala': 'Kalimantan Selatan',
    'barito selatan': 'Kalimantan Tengah',
    'barito timur': 'Kalimantan Tengah',
    'barito utara': 'Kalimantan Tengah',
    'barru': 'Sulawesi Selatan',
    'batam': 'Kepulauan Riau',
    'batang': 'Jawa Tengah',
    'batanghari': 'Jambi',
    'batu': 'Jawa Timur',
    'batu bara': 'Sumatera Utara',
    'bau bau': 'Sulawesi Tenggara',
    'bekasi': 'Jawa Barat',
    'belitung': 'Kepulauan Bangka Belitung',
    'belitung timur': 'Kepulauan Bangka Belitung',
    'belu': 'Nusa Tenggara Timur',
    'bener meriah': 'Aceh',
    'bengkalis': 'Riau',
    'bengkayang': 'Kalimantan Barat',
    'bengkulu': 'Bengkulu',
    'bengkulu selatan': 'Bengkulu',
    'bengkulu tengah': 'Bengkulu',
    'bengkulu utara': 'Bengkulu',
    'berau': 'Kalimantan Timur',
    'biak numfor': 'Papua',
    'bima': 'Nusa Tenggara Barat',
    'binjai': 'Sumatera Utara',
    'bintan': 'Kepulauan Riau',
    'bireuen': 'Aceh',
    'bitung': 'Sulawesi Utara',
    'blitar': 'Jawa Timur',
    'blora': 'Jawa Tengah',
    'boalemo': 'Gorontalo',
    'bogor': 'Jawa Barat',
    'bojonegoro': 'Jawa Timur',
    'bolaang mongondow': 'Sulawesi Utara',
    'bolaang mongondow selatan': 'Sulawesi Utara',
    'bolaang mongondow timur': 'Sulawesi Utara',
    'bolaang mongondow utara': 'Sulawesi Utara',
    'bombana': 'Sulawesi Tenggara',
    'bondowoso': 'Jawa Timur',
    'bone': 'Sulawesi Selatan',
    'bone bolango': 'Gorontalo',
    'bontang': 'Kalimantan Timur',
    'boven digoel': 'Papua Selatan',
    'boyolali': 'Jawa Tengah',
    'brebes': 'Jawa Tengah',
    'bukittinggi': 'Sumatera Barat',
    'buleleng': 'Bali',
    'bulukumba': 'Sulawesi Selatan',
    'bulungan': 'Kalimantan Utara',
    'bungo': 'Jambi',
    'buol': 'Sulawesi Tengah',
    'buru': 'Maluku',
    'buru selatan': 'Maluku',
    'buton': 'Sulawesi Tenggara',
    'buton selatan': 'Sulawesi Tenggara',
    'buton tengah': 'Sulawesi Tenggara',
    'buton utara': 'Sulawesi Tenggara',
    'ciamis': 'Jawa Barat',
    'cianjur': 'Jawa Barat',
    'cilacap': 'Jawa Tengah',
    'cilegon': 'Banten',
    'cimahi': 'Jawa Barat',
    'cirebon': 'Jawa Barat',
    'dairi': 'Sumatera Utara',
    'deiyai': 'Papua Tengah',
    'deli serdang': 'Sumatera Utara',
    'demak': 'Jawa Tengah',
    'denpasar': 'Bali',
    'depok': 'Jawa Barat',
    'dharmasraya': 'Sumatera Barat',
    'dogiyai': 'Papua Tengah',
    'dompu': 'Nusa Tenggara Barat',
    'donggala': 'Sulawesi Tengah',
    'dumai': 'Riau',
    'empat lawang': 'Sumatera Selatan',
    'ende': 'Nusa Tenggara Timur',
    'enrekang': 'Sulawesi Selatan',
    'fak fak': 'Papua Barat',
    'flores timur': 'Nusa Tenggara Timur',
    'garut': 'Jawa Barat',
    'gayo lues': 'Aceh',
    'gianyar': 'Bali',
    'gorontalo': 'Gorontalo',
    'gorontalo utara': 'Gorontalo',
    'gowa': 'Sulawesi Selatan',
    'gresik': 'Jawa Timur',
    'grobogan': 'Jawa Tengah',
    'gunung mas': 'Kalimantan Tengah',
    'gunungkidul': 'DI Yogyakarta',
    'gunungsitoli': 'Sumatera Utara',
    'halmahera barat': 'Maluku Utara',
    'halmahera selatan': 'Maluku Utara',
    'halmahera tengah': 'Maluku Utara',
    'halmahera timur': 'Maluku Utara',
    'halmahera utara': 'Maluku Utara',
    'hulu sungai selatan': 'Kalimantan Selatan',
    'hulu sungai tengah': 'Kalimantan Selatan',
    'hulu sungai utara': 'Kalimantan Selatan',
    'humbang hasundutan': 'Sumatera Utara',
    'indragiri hilir': 'Riau',
    'indragiri hulu': 'Riau',
    'indramayu': 'Jawa Barat',
    'intan jaya': 'Papua Tengah',
    'jakarta barat': 'DKI Jakarta',
    'jakarta pusat': 'DKI Jakarta',
    'jakarta selatan': 'DKI Jakarta',
    'jakarta timur': 'DKI Jakarta',
    'jakarta utara': 'DKI Jakarta',
    'jambi': 'Jambi',
    'jayapura': 'Papua',
    'jayawijaya': 'Papua Pegunungan',
    'jember': 'Jawa Timur',
    'jembrana': 'Bali',
    'jeneponto': 'Sulawesi Selatan',
    'jepara': 'Jawa Tengah',
    'jombang': 'Jawa Timur',
    'kab pegunungan bintang': 'Papua Pegunungan',
    'kab timor tengah selatan': 'Nusa Tenggara Timur',
    'kab. aceh barat': 'Aceh',
    'kab. aceh barat daya': 'Aceh',
    'kab. aceh besar': 'Aceh',
    'kab. aceh jaya': 'Aceh',
    'kab. aceh selatan': 'Aceh',
    'kab. aceh singkil': 'Aceh',
    'kab. aceh tamiang': 'Aceh',
    'kab. aceh tengah': 'Aceh',
    'kab. aceh tenggara': 'Aceh',
    'kab. aceh timur': 'Aceh',
    'kab. aceh utara': 'Aceh',
    'kab. adm. kep. seribu': 'DKI Jakarta',
    'kab. agam': 'Sumatera Barat',
    'kab. alor': 'Nusa Tenggara Timur',
    'kab. asahan': 'Sumatera Utara',
    'kab. asmat': 'Papua Selatan',
    'kab. badung': 'Bali',
    'kab. balangan': 'Kalimantan Selatan',
    'kab. bandung': 'Jawa Barat',
    'kab. bandung barat': 'Jawa Barat',
    'kab. banggai': 'Sulawesi Tengah',
    'kab. banggai kepulauan': 'Sulawesi Tengah',
    'kab. banggai laut': 'Sulawesi Tengah',
    'kab. bangka': 'Kepulauan Bangka Belitung',
    'kab. bangka barat': 'Kepulauan Bangka Belitung',
    'kab. bangka selatan': 'Kepulauan Bangka Belitung',
    'kab. bangka tengah': 'Kepulauan Bangka Belitung',
    'kab. bangkalan': 'Jawa Timur',
    'kab. bangli': 'Bali',
    'kab. banjar': 'Kalimantan Selatan',
    'kab. banjarnegara': 'Jawa Tengah',
    'kab. bantaeng': 'Sulawesi Selatan',
    'kab. bantul': 'DI Yogyakarta',
    'kab. banyuasin': 'Sumatera Selatan',
    'kab. banyumas': 'Jawa Tengah',
    'kab. banyuwangi': 'Jawa Timur',
    'kab. barito kuala': 'Kalimantan Selatan',
    'kab. barito selatan': 'Kalimantan Tengah',
    'kab. barito timur': 'Kalimantan Tengah',
    'kab. barito utara': 'Kalimantan Tengah',
    'kab. barru': 'Sulawesi Selatan',
    'kab. batang': 'Jawa Tengah',
    'kab. batanghari': 'Jambi',
    'kab. batu bara': 'Sumatera Utara',
    'kab. bekasi': 'Jawa Barat',
    'kab. belitung': 'Kepulauan Bangka Belitung',
    'kab. belitung timur': 'Kepulauan Bangka Belitung',
    'kab. belu': 'Nusa Tenggara Timur',
    'kab. bener meriah': 'Aceh',
    'kab. bengkalis': 'Riau',
    'kab. bengkayang': 'Kalimantan Barat',
    'kab. bengkulu selatan': 'Bengkulu',
    'kab. bengkulu tengah': 'Bengkulu',
    'kab. bengkulu utara': 'Bengkulu',
    'kab. berau': 'Kalimantan Timur',
    'kab. biak numfor': 'Papua',
    'kab. bima': 'Nusa Tenggara Barat',
    'kab. bintan': 'Kepulauan Riau',
    'kab. bireuen': 'Aceh',
    'kab. blitar': 'Jawa Timur',
    'kab. blora': 'Jawa Tengah',
    'kab. boalemo': 'Gorontalo',
    'kab. bogor': 'Jawa Barat',
    'kab. bojonegoro': 'Jawa Timur',
    'kab. bolaang mongondow': 'Sulawesi Utara',
    'kab. bolaang mongondow selatan': 'Sulawesi Utara',
    'kab. bolaang mongondow timur': 'Sulawesi Utara',
    'kab. bolaang mongondow utara': 'Sulawesi Utara',
    'kab. bombana': 'Sulawesi Tenggara',
    'kab. bondowoso': 'Jawa Timur',
    'kab. bone': 'Sulawesi Selatan',
    'kab. bone bolango': 'Gorontalo',
    'kab. boven digoel': 'Papua Selatan',
    'kab. boyolali': 'Jawa Tengah',
    'kab. brebes': 'Jawa Tengah',
    'kab. buleleng': 'Bali',
    'kab. bulukumba': 'Sulawesi Selatan',
    'kab. bulungan': 'Kalimantan Utara',
    'kab. bungo': 'Jambi',
    'kab. buol': 'Sulawesi Tengah',
    'kab. buru': 'Maluku',
    'kab. buru selatan': 'Maluku',
    'kab. buton': 'Sulawesi Tenggara',
    'kab. buton selatan': 'Sulawesi Tenggara',
    'kab. buton tengah': 'Sulawesi Tenggara',
    'kab. buton utara': 'Sulawesi Tenggara',
    'kab. ciamis': 'Jawa Barat',
    'kab. cianjur': 'Jawa Barat',
    'kab. cilacap': 'Jawa Tengah',
    'kab. cirebon': 'Jawa Barat',
    'kab. dairi': 'Sumatera Utara',
    'kab. deiyai': 'Papua Tengah',
    'kab. deli serdang': 'Sumatera Utara',
    'kab. demak': 'Jawa Tengah',
    'kab. dharmasraya': 'Sumatera Barat',
    'kab. dogiyai': 'Papua Tengah',
    'kab. dompu': 'Nusa Tenggara Barat',
    'kab. donggala': 'Sulawesi Tengah',
    'kab. empat lawang': 'Sumatera Selatan',
    'kab. ende': 'Nusa Tenggara Timur',
    'kab. enrekang': 'Sulawesi Selatan',
    'kab. fak fak': 'Papua Barat',
    'kab. flores timur': 'Nusa Tenggara Timur',
    'kab. garut': 'Jawa Barat',
    'kab. gayo lues': 'Aceh',
    'kab. gianyar': 'Bali',
    'kab. gorontalo': 'Gorontalo',
    'kab. gorontalo utara': 'Gorontalo',
    'kab. gowa': 'Sulawesi Selatan',
    'kab. gresik': 'Jawa Timur',
    'kab. grobogan': 'Jawa Tengah',
    'kab. gunung mas': 'Kalimantan Tengah',
    'kab. gunungkidul': 'DI Yogyakarta',
    'kab. halmahera barat': 'Maluku Utara',
    'kab. halmahera selatan': 'Maluku Utara',
    'kab. halmahera tengah': 'Maluku Utara',
    'kab. halmahera timur': 'Maluku Utara',
    'kab. halmahera utara': 'Maluku Utara',
    'kab. hulu sungai selatan': 'Kalimantan Selatan',
    'kab. hulu sungai tengah': 'Kalimantan Selatan',
    'kab. hulu sungai utara': 'Kalimantan Selatan',
    'kab. humbang hasundutan': 'Sumatera Utara',
    'kab. indragiri hilir': 'Riau',
    'kab. indragiri hulu': 'Riau',
    'kab. indramayu': 'Jawa Barat',
    'kab. intan jaya': 'Papua Tengah',
    'kab. jayapura': 'Papua',
    'kab. jayawijaya': 'Papua Pegunungan',
    'kab. jember': 'Jawa Timur',
    'kab. jembrana': 'Bali',
    'kab. jeneponto': 'Sulawesi Selatan',
    'kab. jepara': 'Jawa Tengah',
    'kab. jombang': 'Jawa Timur',
    'kab. kaimana': 'Papua Barat',
    'kab. kampar': 'Riau',
    'kab. kapuas': 'Kalimantan Tengah',
    'kab. kapuas hulu': 'Kalimantan Barat',
    'kab. karanganyar': 'Jawa Tengah',
    'kab. karangasem': 'Bali',
    'kab. karawang': 'Jawa Barat',
    'kab. karimun': 'Kepulauan Riau',
    'kab. karo': 'Sumatera Utara',
    'kab. katingan': 'Kalimantan Tengah',
    'kab. kaur': 'Bengkulu',
    'kab. kayong utara': 'Kalimantan Barat',
    'kab. kebumen': 'Jawa Tengah',
    'kab. kediri': 'Jawa Timur',
    'kab. keerom': 'Papua',
    'kab. kendal': 'Jawa Tengah',
    'kab. kep. siau tagulandang biaro': 'Sulawesi Utara',
    'kab. kepahiang': 'Bengkulu',
    'kab. kepulauan anambas': 'Kepulauan Riau',
    'kab. kepulauan aru': 'Maluku',
    'kab. kepulauan mentawai': 'Sumatera Barat',
    'kab. kepulauan meranti': 'Riau',
    'kab. kepulauan sangihe': 'Sulawesi Utara',
    'kab. kepulauan selayar': 'Sulawesi Selatan',
    'kab. kepulauan sula': 'Maluku Utara',
    'kab. kepulauan talaud': 'Sulawesi Utara',
    'kab. kepulauan tanimbar': 'Maluku',
    'kab. kepulauan yapen': 'Papua',
    'kab. kerinci': 'Jambi',
    'kab. ketapang': 'Kalimantan Barat',
    'kab. klaten': 'Jawa Tengah',
    'kab. klungkung': 'Bali',
    'kab. kolaka': 'Sulawesi Tenggara',
    'kab. kolaka timur': 'Sulawesi Tenggara',
    'kab. kolaka utara': 'Sulawesi Tenggara',
    'kab. konawe': 'Sulawesi Tenggara',
    'kab. konawe kepulauan': 'Sulawesi Tenggara',
    'kab. konawe selatan': 'Sulawesi Tenggara',
    'kab. konawe utara': 'Sulawesi Tenggara',
    'kab. kotabaru': 'Kalimantan Selatan',
    'kab. kotawaringin barat': 'Kalimantan Tengah',
    'kab. kotawaringin timur': 'Kalimantan Tengah',
    'kab. kuantan singingi': 'Riau',
    'kab. kubu raya': 'Kalimantan Barat',
    'kab. kudus': 'Jawa Tengah',
    'kab. kulon progo': 'DI Yogyakarta',
    'kab. kuningan': 'Jawa Barat',
    'kab. kupang': 'Nusa Tenggara Timur',
    'kab. kutai barat': 'Kalimantan Timur',
    'kab. kutai kartanegara': 'Kalimantan Timur',
    'kab. kutai timur': 'Kalimantan Timur',
    'kab. labuhanbatu': 'Sumatera Utara',
    'kab. labuhanbatu selatan': 'Sumatera Utara',
    'kab. labuhanbatu utara': 'Sumatera Utara',
    'kab. lahat': 'Sumatera Selatan',
    'kab. lamandau': 'Kalimantan Tengah',
    'kab. lamongan': 'Jawa Timur',
    'kab. lampung barat': 'Lampung',
    'kab. lampung selatan': 'Lampung',
    'kab. lampung tengah': 'Lampung',
    'kab. lampung timur': 'Lampung',
    'kab. lampung utara': 'Lampung',
    'kab. landak': 'Kalimantan Barat',
    'kab. langkat': 'Sumatera Utara',
    'kab. lanny jaya': 'Papua Pegunungan',
    'kab. lebak': 'Banten',
    'kab. lebong': 'Bengkulu',
    'kab. lembata': 'Nusa Tenggara Timur',
    'kab. lima puluh kota': 'Sumatera Barat',
    'kab. lingga': 'Kepulauan Riau',
    'kab. lombok barat': 'Nusa Tenggara Barat',
    'kab. lombok tengah': 'Nusa Tenggara Barat',
    'kab. lombok timur': 'Nusa Tenggara Barat',
    'kab. lombok utara': 'Nusa Tenggara Barat',
    'kab. lumajang': 'Jawa Timur',
    'kab. luwu': 'Sulawesi Selatan',
    'kab. luwu timur': 'Sulawesi Selatan',
    'kab. luwu utara': 'Sulawesi Selatan',
    'kab. madiun': 'Jawa Timur',
    'kab. magelang': 'Jawa Tengah',
    'kab. magetan': 'Jawa Timur',
    'kab. mahakam ulu': 'Kalimantan Timur',
    'kab. majalengka': 'Jawa Barat',
    'kab. majene': 'Sulawesi Barat',
    'kab. malaka': 'Nusa Tenggara Timur',
    'kab. malang': 'Jawa Timur',
    'kab. malinau': 'Kalimantan Utara',
    'kab. maluku barat daya': 'Maluku',
    'kab. maluku tengah': 'Maluku',
    'kab. maluku tenggara': 'Maluku',
    'kab. mamasa': 'Sulawesi Barat',
    'kab. mamberamo raya': 'Papua',
    'kab. mamberamo tengah': 'Papua Pegunungan',
    'kab. mamuju': 'Sulawesi Barat',
    'kab. mamuju tengah': 'Sulawesi Barat',
    'kab. mandailing natal': 'Sumatera Utara',
    'kab. manggarai': 'Nusa Tenggara Timur',
    'kab. manggarai barat': 'Nusa Tenggara Timur',
    'kab. manggarai timur': 'Nusa Tenggara Timur',
    'kab. manokwari': 'Papua Barat',
    'kab. manokwari selatan': 'Papua Barat',
    'kab. mappi': 'Papua Selatan',
    'kab. maros': 'Sulawesi Selatan',
    'kab. maybrat': 'Papua Barat Daya',
    'kab. melawi': 'Kalimantan Barat',
    'kab. mempawah': 'Kalimantan Barat',
    'kab. merangin': 'Jambi',
    'kab. merauke': 'Papua Selatan',
    'kab. mesuji': 'Lampung',
    'kab. mimika': 'Papua Tengah',
    'kab. minahasa': 'Sulawesi Utara',
    'kab. minahasa selatan': 'Sulawesi Utara',
    'kab. minahasa tenggara': 'Sulawesi Utara',
    'kab. minahasa utara': 'Sulawesi Utara',
    'kab. mojokerto': 'Jawa Timur',
    'kab. morowali': 'Sulawesi Tengah',
    'kab. morowali utara': 'Sulawesi Tengah',
    'kab. muara enim': 'Sumatera Selatan',
    'kab. muaro jambi': 'Jambi',
    'kab. muko muko': 'Bengkulu',
    'kab. muna': 'Sulawesi Tenggara',
    'kab. muna barat': 'Sulawesi Tenggara',
    'kab. murung raya': 'Kalimantan Tengah',
    'kab. musi banyuasin': 'Sumatera Selatan',
    'kab. musi rawas': 'Sumatera Selatan',
    'kab. musi rawas utara': 'Sumatera Selatan',
    'kab. nabire': 'Papua Tengah',
    'kab. nagan raya': 'Aceh',
    'kab. nagekeo': 'Nusa Tenggara Timur',
    'kab. natuna': 'Kepulauan Riau',
    'kab. nduga': 'Papua Pegunungan',
    'kab. ngada': 'Nusa Tenggara Timur',
    'kab. nganjuk': 'Jawa Timur',
    'kab. ngawi': 'Jawa Timur',
    'kab. nias': 'Sumatera Utara',
    'kab. nias barat': 'Sumatera Utara',
    'kab. nias selatan': 'Sumatera Utara',
    'kab. nias utara': 'Sumatera Utara',
    'kab. nunukan': 'Kalimantan Utara',
    'kab. ogan ilir': 'Sumatera Selatan',
    'kab. ogan komering ilir': 'Sumatera Selatan',
    'kab. ogan komering ulu': 'Sumatera Selatan',
    'kab. ogan komering ulu selatan': 'Sumatera Selatan',
    'kab. ogan komering ulu timur': 'Sumatera Selatan',
    'kab. pacitan': 'Jawa Timur',
    'kab. padang lawas': 'Sumatera Utara',
    'kab. padang lawas utara': 'Sumatera Utara',
    'kab. padang pariaman': 'Sumatera Barat',
    'kab. pakpak bharat': 'Sumatera Utara',
    'kab. pamekasan': 'Jawa Timur',
    'kab. pandeglang': 'Banten',
    'kab. pangandaran': 'Jawa Barat',
    'kab. pangkajene dan kepulauan': 'Sulawesi Selatan',
    'kab. paniai': 'Papua Tengah',
    'kab. parigi moutong': 'Sulawesi Tengah',
    'kab. pasaman': 'Sumatera Barat',
    'kab. pasaman barat': 'Sumatera Barat',
    'kab. pasangkayu': 'Sulawesi Barat',
    'kab. paser': 'Kalimantan Timur',
    'kab. pasuruan': 'Jawa Timur',
    'kab. pati': 'Jawa Tengah',
    'kab. pegunungan arfak': 'Papua Barat',
    'kab. pekalongan': 'Jawa Tengah',
    'kab. pelalawan': 'Riau',
    'kab. pemalang': 'Jawa Tengah',
    'kab. penajam paser utara': 'Kalimantan Timur',
    'kab. penukal abab lematang ilir': 'Sumatera Selatan',
    'kab. pesawaran': 'Lampung',
    'kab. pesisir barat': 'Lampung',
    'kab. pesisir selatan': 'Sumatera Barat',
    'kab. pidie': 'Aceh',
    'kab. pidie jaya': 'Aceh',
    'kab. pinrang': 'Sulawesi Selatan',
    'kab. pohuwato': 'Gorontalo',
    'kab. polewali mandar': 'Sulawesi Barat',
    'kab. ponorogo': 'Jawa Timur',
    'kab. poso': 'Sulawesi Tengah',
    'kab. pringsewu': 'Lampung',
    'kab. probolinggo': 'Jawa Timur',
    'kab. pulang pisau': 'Kalimantan Tengah',
    'kab. pulau morotai': 'Maluku Utara',
    'kab. pulau taliabu': 'Maluku Utara',
    'kab. puncak': 'Papua Tengah',
    'kab. puncak jaya': 'Papua Tengah',
    'kab. purbalingga': 'Jawa Tengah',
    'kab. purwakarta': 'Jawa Barat',
    'kab. purworejo': 'Jawa Tengah',
    'kab. raja ampat': 'Papua Barat Daya',
    'kab. rejang lebong': 'Bengkulu',
    'kab. rembang': 'Jawa Tengah',
    'kab. rokan hilir': 'Riau',
    'kab. rokan hulu': 'Riau',
    'kab. rote ndao': 'Nusa Tenggara Timur',
    'kab. sabu raijua': 'Nusa Tenggara Timur',
    'kab. sambas': 'Kalimantan Barat',
    'kab. samosir': 'Sumatera Utara',
    'kab. sampang': 'Jawa Timur',
    'kab. sanggau': 'Kalimantan Barat',
    'kab. sarmi': 'Papua',
    'kab. sarolangun': 'Jambi',
    'kab. sekadau': 'Kalimantan Barat',
    'kab. seluma': 'Bengkulu',
    'kab. semarang': 'Jawa Tengah',
    'kab. seram bagian barat': 'Maluku',
    'kab. seram bagian timur': 'Maluku',
    'kab. serang': 'Banten',
    'kab. serdang bedagai': 'Sumatera Utara',
    'kab. seruyan': 'Kalimantan Tengah',
    'kab. siak': 'Riau',
    'kab. sidenreng rappang': 'Sulawesi Selatan',
    'kab. sidoarjo': 'Jawa Timur',
    'kab. sigi': 'Sulawesi Tengah',
    'kab. sijunjung': 'Sumatera Barat',
    'kab. sikka': 'Nusa Tenggara Timur',
    'kab. simalungun': 'Sumatera Utara',
    'kab. simeulue': 'Aceh',
    'kab. sinjai': 'Sulawesi Selatan',
    'kab. sintang': 'Kalimantan Barat',
    'kab. situbondo': 'Jawa Timur',
    'kab. sleman': 'DI Yogyakarta',
    'kab. solok': 'Sumatera Barat',
    'kab. solok selatan': 'Sumatera Barat',
    'kab. soppeng': 'Sulawesi Selatan',
    'kab. sorong': 'Papua Barat Daya',
    'kab. sorong selatan': 'Papua Barat Daya',
    'kab. sragen': 'Jawa Tengah',
    'kab. subang': 'Jawa Barat',
    'kab. sukabumi': 'Jawa Barat',
    'kab. sukamara': 'Kalimantan Tengah',
    'kab. sukoharjo': 'Jawa Tengah',
    'kab. sumba barat': 'Nusa Tenggara Timur',
    'kab. sumba barat daya': 'Nusa Tenggara Timur',
    'kab. sumba tengah': 'Nusa Tenggara Timur',
    'kab. sumba timur': 'Nusa Tenggara Timur',
    'kab. sumbawa': 'Nusa Tenggara Barat',
    'kab. sumbawa barat': 'Nusa Tenggara Barat',
    'kab. sumedang': 'Jawa Barat',
    'kab. sumenep': 'Jawa Timur',
    'kab. supiori': 'Papua',
    'kab. tabalong': 'Kalimantan Selatan',
    'kab. tabanan': 'Bali',
    'kab. takalar': 'Sulawesi Selatan',
    'kab. tambrauw': 'Papua Barat Daya',
    'kab. tana tidung': 'Kalimantan Utara',
    'kab. tana toraja': 'Sulawesi Selatan',
    'kab. tanah bumbu': 'Kalimantan Selatan',
    'kab. tanah datar': 'Sumatera Barat',
    'kab. tanah laut': 'Kalimantan Selatan',
    'kab. tangerang': 'Banten',
    'kab. tanggamus': 'Lampung',
    'kab. tanjung jabung barat': 'Jambi',
    'kab. tanjung jabung timur': 'Jambi',
    'kab. tapanuli selatan': 'Sumatera Utara',
    'kab. tapanuli tengah': 'Sumatera Utara',
    'kab. tapanuli utara': 'Sumatera Utara',
    'kab. tapin': 'Kalimantan Selatan',
    'kab. tasikmalaya': 'Jawa Barat',
    'kab. tebo': 'Jambi',
    'kab. tegal': 'Jawa Tengah',
    'kab. teluk bintuni': 'Papua Barat',
    'kab. teluk wondama': 'Papua Barat',
    'kab. temanggung': 'Jawa Tengah',
    'kab. timor tengah utara': 'Nusa Tenggara Timur',
    'kab. toba': 'Sumatera Utara',
    'kab. tojo una una': 'Sulawesi Tengah',
    'kab. toli toli': 'Sulawesi Tengah',
    'kab. tolikara': 'Papua Pegunungan',
    'kab. toraja utara': 'Sulawesi Selatan',
    'kab. trenggalek': 'Jawa Timur',
    'kab. tuban': 'Jawa Timur',
    'kab. tulang bawang': 'Lampung',
    'kab. tulang bawang barat': 'Lampung',
    'kab. tulungagung': 'Jawa Timur',
    'kab. wajo': 'Sulawesi Selatan',
    'kab. wakatobi': 'Sulawesi Tenggara',
    'kab. waropen': 'Papua',
    'kab. way kanan': 'Lampung',
    'kab. wonogiri': 'Jawa Tengah',
    'kab. wonosobo': 'Jawa Tengah',
    'kab. yahukimo': 'Papua Pegunungan',
    'kab. yalimo': 'Papua Pegunungan',
    'kaimana': 'Papua Barat',
    'kampar': 'Riau',
    'kapuas': 'Kalimantan Tengah',
    'kapuas hulu': 'Kalimantan Barat',
    'karanganyar': 'Jawa Tengah',
    'karangasem': 'Bali',
    'karawang': 'Jawa Barat',
    'karimun': 'Kepulauan Riau',
    'karo': 'Sumatera Utara',
    'katingan': 'Kalimantan Tengah',
    'kaur': 'Bengkulu',
    'kayong utara': 'Kalimantan Barat',
    'kebumen': 'Jawa Tengah',
    'kediri': 'Jawa Timur',
    'keerom': 'Papua',
    'kendal': 'Jawa Tengah',
    'kendari': 'Sulawesi Tenggara',
    'kep. siau tagulandang biaro': 'Sulawesi Utara',
    'kepahiang': 'Bengkulu',
    'kepulauan anambas': 'Kepulauan Riau',
    'kepulauan aru': 'Maluku',
    'kepulauan mentawai': 'Sumatera Barat',
    'kepulauan meranti': 'Riau',
    'kepulauan sangihe': 'Sulawesi Utara',
    'kepulauan selayar': 'Sulawesi Selatan',
    'kepulauan sula': 'Maluku Utara',
    'kepulauan talaud': 'Sulawesi Utara',
    'kepulauan tanimbar': 'Maluku',
    'kepulauan yapen': 'Papua',
    'kerinci': 'Jambi',
    'ketapang': 'Kalimantan Barat',
    'klaten': 'Jawa Tengah',
    'klungkung': 'Bali',
    'kolaka': 'Sulawesi Tenggara',
    'kolaka timur': 'Sulawesi Tenggara',
    'kolaka utara': 'Sulawesi Tenggara',
    'konawe': 'Sulawesi Tenggara',
    'konawe kepulauan': 'Sulawesi Tenggara',
    'konawe selatan': 'Sulawesi Tenggara',
    'konawe utara': 'Sulawesi Tenggara',
    'kota adm. jakarta barat': 'DKI Jakarta',
    'kota adm. jakarta pusat': 'DKI Jakarta',
    'kota adm. jakarta selatan': 'DKI Jakarta',
    'kota adm. jakarta timur': 'DKI Jakarta',
    'kota adm. jakarta utara': 'DKI Jakarta',
    'kota ambon': 'Maluku',
    'kota balikpapan': 'Kalimantan Timur',
    'kota banda aceh': 'Aceh',
    'kota bandar lampung': 'Lampung',
    'kota bandung': 'Jawa Barat',
    'kota banjar': 'Jawa Barat',
    'kota banjarbaru': 'Kalimantan Selatan',
    'kota banjarmasin': 'Kalimantan Selatan',
    'kota batam': 'Kepulauan Riau',
    'kota batu': 'Jawa Timur',
    'kota bau bau': 'Sulawesi Tenggara',
    'kota bekasi': 'Jawa Barat',
    'kota bengkulu': 'Bengkulu',
    'kota bima': 'Nusa Tenggara Barat',
    'kota binjai': 'Sumatera Utara',
    'kota bitung': 'Sulawesi Utara',
    'kota blitar': 'Jawa Timur',
    'kota bogor': 'Jawa Barat',
    'kota bontang': 'Kalimantan Timur',
    'kota bukittinggi': 'Sumatera Barat',
    'kota cilegon': 'Banten',
    'kota cimahi': 'Jawa Barat',
    'kota cirebon': 'Jawa Barat',
    'kota denpasar': 'Bali',
    'kota depok': 'Jawa Barat',
    'kota dumai': 'Riau',
    'kota gorontalo': 'Gorontalo',
    'kota gunungsitoli': 'Sumatera Utara',
    'kota jambi': 'Jambi',
    'kota jayapura': 'Papua',
    'kota kediri': 'Jawa Timur',
    'kota kendari': 'Sulawesi Tenggara',
    'kota kotamobagu': 'Sulawesi Utara',
    'kota kupang': 'Nusa Tenggara Timur',
    'kota langsa': 'Aceh',
    'kota lhokseumawe': 'Aceh',
    'kota lubuk linggau': 'Sumatera Selatan',
    'kota madiun': 'Jawa Timur',
    'kota magelang': 'Jawa Tengah',
    'kota makassar': 'Sulawesi Selatan',
    'kota malang': 'Jawa Timur',
    'kota manado': 'Sulawesi Utara',
    'kota mataram': 'Nusa Tenggara Barat',
    'kota medan': 'Sumatera Utara',
    'kota metro': 'Lampung',
    'kota mojokerto': 'Jawa Timur',
    'kota padang': 'Sumatera Barat',
    'kota padang panjang': 'Sumatera Barat',
    'kota padang sidempuan': 'Sumatera Utara',
    'kota pagar alam': 'Sumatera Selatan',
    'kota palangkaraya': 'Kalimantan Tengah',
    'kota palembang': 'Sumatera Selatan',
    'kota palopo': 'Sulawesi Selatan',
    'kota palu': 'Sulawesi Tengah',
    'kota pangkal pinang': 'Kepulauan Bangka Belitung',
    'kota parepare': 'Sulawesi Selatan',
    'kota pariaman': 'Sumatera Barat',
    'kota pasuruan': 'Jawa Timur',
    'kota payakumbuh': 'Sumatera Barat',
    'kota pekalongan': 'Jawa Tengah',
    'kota pekanbaru': 'Riau',
    'kota pematangsiantar': 'Sumatera Utara',
    'kota pontianak': 'Kalimantan Barat',
    'kota prabumulih': 'Sumatera Selatan',
    'kota probolinggo': 'Jawa Timur',
    'kota sabang': 'Aceh',
    'kota salatiga': 'Jawa Tengah',
    'kota samarinda': 'Kalimantan Timur',
    'kota sawahlunto': 'Sumatera Barat',
    'kota semarang': 'Jawa Tengah',
    'kota serang': 'Banten',
    'kota sibolga': 'Sumatera Utara',
    'kota singkawang': 'Kalimantan Barat',
    'kota solok': 'Sumatera Barat',
    'kota sorong': 'Papua Barat Daya',
    'kota subulussalam': 'Aceh',
    'kota sukabumi': 'Jawa Barat',
    'kota sungai penuh': 'Jambi',
    'kota surabaya': 'Jawa Timur',
    'kota surakarta': 'Jawa Tengah',
    'kota tangerang': 'Banten',
    'kota tangerang selatan': 'Banten',
    'kota tanjung balai': 'Sumatera Utara',
    'kota tanjung pinang': 'Kepulauan Riau',
    'kota tarakan': 'Kalimantan Utara',
    'kota tasikmalaya': 'Jawa Barat',
    'kota tebing tinggi': 'Sumatera Utara',
    'kota tegal': 'Jawa Tengah',
    'kota ternate': 'Maluku Utara',
    'kota tidore kepulauan': 'Maluku Utara',
    'kota tomohon': 'Sulawesi Utara',
    'kota tual': 'Maluku',
    'kota yogyakarta': 'DI Yogyakarta',
    'kotabaru': 'Kalimantan Selatan',
    'kotamobagu': 'Sulawesi Utara',
    'kotawaringin barat': 'Kalimantan Tengah',
    'kotawaringin timur': 'Kalimantan Tengah',
    'kuantan singingi': 'Riau',
    'kubu raya': 'Kalimantan Barat',
    'kudus': 'Jawa Tengah',
    'kulon progo': 'DI Yogyakarta',
    'kuningan': 'Jawa Barat',
    'kupang': 'Nusa Tenggara Timur',
    'kutai barat': 'Kalimantan Timur',
    'kutai kartanegara': 'Kalimantan Timur',
    'kutai timur': 'Kalimantan Timur',
    'labuhanbatu': 'Sumatera Utara',
    'labuhanbatu selatan': 'Sumatera Utara',
    'labuhanbatu utara': 'Sumatera Utara',
    'lahat': 'Sumatera Selatan',
    'lamandau': 'Kalimantan Tengah',
    'lamongan': 'Jawa Timur',
    'lampung barat': 'Lampung',
    'lampung selatan': 'Lampung',
    'lampung tengah': 'Lampung',
    'lampung timur': 'Lampung',
    'lampung utara': 'Lampung',
    'landak': 'Kalimantan Barat',
    'langkat': 'Sumatera Utara',
    'langsa': 'Aceh',
    'lanny jaya': 'Papua Pegunungan',
    'lebak': 'Banten',
    'lebong': 'Bengkulu',
    'lembata': 'Nusa Tenggara Timur',
    'lhokseumawe': 'Aceh',
    'lima puluh kota': 'Sumatera Barat',
    'lingga': 'Kepulauan Riau',
    'lombok barat': 'Nusa Tenggara Barat',
    'lombok tengah': 'Nusa Tenggara Barat',
    'lombok timur': 'Nusa Tenggara Barat',
    'lombok utara': 'Nusa Tenggara Barat',
    'lubuk linggau': 'Sumatera Selatan',
    'lumajang': 'Jawa Timur',
    'luwu': 'Sulawesi Selatan',
    'luwu timur': 'Sulawesi Selatan',
    'luwu utara': 'Sulawesi Selatan',
    'madiun': 'Jawa Timur',
    'magelang': 'Jawa Tengah',
    'magetan': 'Jawa Timur',
    'mahakam ulu': 'Kalimantan Timur',
    'majalengka': 'Jawa Barat',
    'majene': 'Sulawesi Barat',
    'makassar': 'Sulawesi Selatan',
    'malaka': 'Nusa Tenggara Timur',
    'malang': 'Jawa Timur',
    'malinau': 'Kalimantan Utara',
    'maluku barat daya': 'Maluku',
    'maluku tengah': 'Maluku',
    'maluku tenggara': 'Maluku',
    'mamasa': 'Sulawesi Barat',
    'mamberamo raya': 'Papua',
    'mamberamo tengah': 'Papua Pegunungan',
    'mamuju': 'Sulawesi Barat',
    'mamuju tengah': 'Sulawesi Barat',
    'manado': 'Sulawesi Utara',
    'mandailing natal': 'Sumatera Utara',
    'manggarai': 'Nusa Tenggara Timur',
    'manggarai barat': 'Nusa Tenggara Timur',
    'manggarai timur': 'Nusa Tenggara Timur',
    'manokwari': 'Papua Barat',
    'manokwari selatan': 'Papua Barat',
    'mappi': 'Papua Selatan',
    'maros': 'Sulawesi Selatan',
    'mataram': 'Nusa Tenggara Barat',
    'maybrat': 'Papua Barat Daya',
    'medan': 'Sumatera Utara',
    'melawi': 'Kalimantan Barat',
    'mempawah': 'Kalimantan Barat',
    'merangin': 'Jambi',
    'merauke': 'Papua Selatan',
    'mesuji': 'Lampung',
    'metro': 'Lampung',
    'mimika': 'Papua Tengah',
    'minahasa': 'Sulawesi Utara',
    'minahasa selatan': 'Sulawesi Utara',
    'minahasa tenggara': 'Sulawesi Utara',
    'minahasa utara': 'Sulawesi Utara',
    'mojokerto': 'Jawa Timur',
    'morowali': 'Sulawesi Tengah',
    'morowali utara': 'Sulawesi Tengah',
    'muara enim': 'Sumatera Selatan',
    'muaro jambi': 'Jambi',
    'muko muko': 'Bengkulu',
    'muna': 'Sulawesi Tenggara',
    'muna barat': 'Sulawesi Tenggara',
    'murung raya': 'Kalimantan Tengah',
    'musi banyuasin': 'Sumatera Selatan',
    'musi rawas': 'Sumatera Selatan',
    'musi rawas utara': 'Sumatera Selatan',
    'nabire': 'Papua Tengah',
    'nagan raya': 'Aceh',
    'nagekeo': 'Nusa Tenggara Timur',
    'natuna': 'Kepulauan Riau',
    'nduga': 'Papua Pegunungan',
    'ngada': 'Nusa Tenggara Timur',
    'nganjuk': 'Jawa Timur',
    'ngawi': 'Jawa Timur',
    'nias': 'Sumatera Utara',
    'nias barat': 'Sumatera Utara',
    'nias selatan': 'Sumatera Utara',
    'nias utara': 'Sumatera Utara',
    'nunukan': 'Kalimantan Utara',
    'ogan ilir': 'Sumatera Selatan',
    'ogan komering ilir': 'Sumatera Selatan',
    'ogan komering ulu': 'Sumatera Selatan',
    'ogan komering ulu selatan': 'Sumatera Selatan',
    'ogan komering ulu timur': 'Sumatera Selatan',
    'pacitan': 'Jawa Timur',
    'padang': 'Sumatera Barat',
    'padang lawas': 'Sumatera Utara',
    'padang lawas utara': 'Sumatera Utara',
    'padang panjang': 'Sumatera Barat',
    'padang pariaman': 'Sumatera Barat',
    'padang sidempuan': 'Sumatera Utara',
    'pagar alam': 'Sumatera Selatan',
    'pakpak bharat': 'Sumatera Utara',
    'palangkaraya': 'Kalimantan Tengah',
    'palembang': 'Sumatera Selatan',
    'palopo': 'Sulawesi Selatan',
    'palu': 'Sulawesi Tengah',
    'pamekasan': 'Jawa Timur',
    'pandeglang': 'Banten',
    'pangandaran': 'Jawa Barat',
    'pangkajene dan kepulauan': 'Sulawesi Selatan',
    'pangkal pinang': 'Kepulauan Bangka Belitung',
    'paniai': 'Papua Tengah',
    'parepare': 'Sulawesi Selatan',
    'pariaman': 'Sumatera Barat',
    'parigi moutong': 'Sulawesi Tengah',
    'pasaman': 'Sumatera Barat',
    'pasaman barat': 'Sumatera Barat',
    'pasangkayu': 'Sulawesi Barat',
    'paser': 'Kalimantan Timur',
    'pasuruan': 'Jawa Timur',
    'pati': 'Jawa Tengah',
    'payakumbuh': 'Sumatera Barat',
    'pegunungan arfak': 'Papua Barat',
    'pegunungan bintang': 'Papua Pegunungan',
    'pekalongan': 'Jawa Tengah',
    'pekanbaru': 'Riau',
    'pelalawan': 'Riau',
    'pemalang': 'Jawa Tengah',
    'pematangsiantar': 'Sumatera Utara',
    'penajam paser utara': 'Kalimantan Timur',
    'penukal abab lematang ilir': 'Sumatera Selatan',
    'pesawaran': 'Lampung',
    'pesisir barat': 'Lampung',
    'pesisir selatan': 'Sumatera Barat',
    'pidie': 'Aceh',
    'pidie jaya': 'Aceh',
    'pinrang': 'Sulawesi Selatan',
    'pohuwato': 'Gorontalo',
    'polewali mandar': 'Sulawesi Barat',
    'ponorogo': 'Jawa Timur',
    'pontianak': 'Kalimantan Barat',
    'poso': 'Sulawesi Tengah',
    'prabumulih': 'Sumatera Selatan',
    'pringsewu': 'Lampung',
    'probolinggo': 'Jawa Timur',
    'pulang pisau': 'Kalimantan Tengah',
    'pulau morotai': 'Maluku Utara',
    'pulau taliabu': 'Maluku Utara',
    'puncak': 'Papua Tengah',
    'puncak jaya': 'Papua Tengah',
    'purbalingga': 'Jawa Tengah',
    'purwakarta': 'Jawa Barat',
    'purworejo': 'Jawa Tengah',
    'raja ampat': 'Papua Barat Daya',
    'rejang lebong': 'Bengkulu',
    'rembang': 'Jawa Tengah',
    'rokan hilir': 'Riau',
    'rokan hulu': 'Riau',
    'rote ndao': 'Nusa Tenggara Timur',
    'sabang': 'Aceh',
    'sabu raijua': 'Nusa Tenggara Timur',
    'salatiga': 'Jawa Tengah',
    'samarinda': 'Kalimantan Timur',
    'sambas': 'Kalimantan Barat',
    'samosir': 'Sumatera Utara',
    'sampang': 'Jawa Timur',
    'sanggau': 'Kalimantan Barat',
    'sarmi': 'Papua',
    'sarolangun': 'Jambi',
    'sawahlunto': 'Sumatera Barat',
    'sekadau': 'Kalimantan Barat',
    'seluma': 'Bengkulu',
    'semarang': 'Jawa Tengah',
    'seram bagian barat': 'Maluku',
    'seram bagian timur': 'Maluku',
    'serang': 'Banten',
    'serdang bedagai': 'Sumatera Utara',
    'seruyan': 'Kalimantan Tengah',
    'siak': 'Riau',
    'sibolga': 'Sumatera Utara',
    'sidenreng rappang': 'Sulawesi Selatan',
    'sidoarjo': 'Jawa Timur',
    'sigi': 'Sulawesi Tengah',
    'sijunjung': 'Sumatera Barat',
    'sikka': 'Nusa Tenggara Timur',
    'simalungun': 'Sumatera Utara',
    'simeulue': 'Aceh',
    'singkawang': 'Kalimantan Barat',
    'sinjai': 'Sulawesi Selatan',
    'sintang': 'Kalimantan Barat',
    'situbondo': 'Jawa Timur',
    'sleman': 'DI Yogyakarta',
    'solok': 'Sumatera Barat',
    'solok selatan': 'Sumatera Barat',
    'soppeng': 'Sulawesi Selatan',
    'sorong': 'Papua Barat Daya',
    'sorong selatan': 'Papua Barat Daya',
    'sragen': 'Jawa Tengah',
    'subang': 'Jawa Barat',
    'subulussalam': 'Aceh',
    'sukabumi': 'Jawa Barat',
    'sukamara': 'Kalimantan Tengah',
    'sukoharjo': 'Jawa Tengah',
    'sumba barat': 'Nusa Tenggara Timur',
    'sumba barat daya': 'Nusa Tenggara Timur',
    'sumba tengah': 'Nusa Tenggara Timur',
    'sumba timur': 'Nusa Tenggara Timur',
    'sumbawa': 'Nusa Tenggara Barat',
    'sumbawa barat': 'Nusa Tenggara Barat',
    'sumedang': 'Jawa Barat',
    'sumenep': 'Jawa Timur',
    'sungai penuh': 'Jambi',
    'supiori': 'Papua',
    'surabaya': 'Jawa Timur',
    'surakarta': 'Jawa Tengah',
    'tabalong': 'Kalimantan Selatan',
    'tabanan': 'Bali',
    'takalar': 'Sulawesi Selatan',
    'tambrauw': 'Papua Barat Daya',
    'tana tidung': 'Kalimantan Utara',
    'tana toraja': 'Sulawesi Selatan',
    'tanah bumbu': 'Kalimantan Selatan',
    'tanah datar': 'Sumatera Barat',
    'tanah laut': 'Kalimantan Selatan',
    'tangerang': 'Banten',
    'tangerang selatan': 'Banten',
    'tanggamus': 'Lampung',
    'tanjung balai': 'Sumatera Utara',
    'tanjung jabung barat': 'Jambi',
    'tanjung jabung timur': 'Jambi',
    'tanjung pinang': 'Kepulauan Riau',
    'tapanuli selatan': 'Sumatera Utara',
    'tapanuli tengah': 'Sumatera Utara',
    'tapanuli utara': 'Sumatera Utara',
    'tapin': 'Kalimantan Selatan',
    'tarakan': 'Kalimantan Utara',
    'tasikmalaya': 'Jawa Barat',
    'tebing tinggi': 'Sumatera Utara',
    'tebo': 'Jambi',
    'tegal': 'Jawa Tengah',
    'teluk bintuni': 'Papua Barat',
    'teluk wondama': 'Papua Barat',
    'temanggung': 'Jawa Tengah',
    'ternate': 'Maluku Utara',
    'tidore kepulauan': 'Maluku Utara',
    'timor tengah selatan': 'Nusa Tenggara Timur',
    'timor tengah utara': 'Nusa Tenggara Timur',
    'toba': 'Sumatera Utara',
    'tojo una una': 'Sulawesi Tengah',
    'toli toli': 'Sulawesi Tengah',
    'tolikara': 'Papua Pegunungan',
    'tomohon': 'Sulawesi Utara',
    'toraja utara': 'Sulawesi Selatan',
    'trenggalek': 'Jawa Timur',
    'tual': 'Maluku',
    'tuban': 'Jawa Timur',
    'tulang bawang': 'Lampung',
    'tulang bawang barat': 'Lampung',
    'tulungagung': 'Jawa Timur',
    'wajo': 'Sulawesi Selatan',
    'wakatobi': 'Sulawesi Tenggara',
    'waropen': 'Papua',
    'way kanan': 'Lampung',
    'wonogiri': 'Jawa Tengah',
    'wonosobo': 'Jawa Tengah',
    'yahukimo': 'Papua Pegunungan',
    'yalimo': 'Papua Pegunungan',
    'yogyakarta': 'DI Yogyakarta',
}
